### PR TITLE
New cli args (reportfile and reportfolder)

### PR DESCRIPTION
**Pull request by mato7d5**
new command line arguments added for cli version of verapdf-apps:
1. reportfile: redirect output from stdout to the file defined by user
2. reportfolder: for each tested pdf/a file create a separate report file in defined folder.

If both of them are defined on command line, then default behavior is switching back to STDOUT.

### CODE REVIEW

**Comment by carlwilson** [comment]
He @mato7d5 and thanks for this, it's needed functionality. I have one question that might require a small adjustment. When the -r (recursive) flag is set and a directory is passed to the CLI the results are all still written to a single directory. This could lead to results been overwritten if there are files of the same name in different parts of the sub-tree. One way to deal with this might be to mirror the directory tree in the result folder structure. I've added a basic example below for clarity, first a simple dir structure to be validated:

    ./dir-to-validate
        - fileA.pdf
        - fileB.pdf
        /sub-dir-to-validate
            - fileA.pdf
            - fileX.pdf
If the command verapdf -r --reportfolder ./validation-results ./dir-to-validate was issued the contents of the final results folder would be:

    ./validation-results
        - fileA.mmr
        - fileB.mmr
        - fileX.mmr
One of the results for fileA.pdf will have been lost, i.e. the one validated first. I've tested this behaviour and it is the case. I'd suggest that the following should be created:

    ./validation-results
        - fileA.mmr
        - fileB.mmr
        /sub-dir-to-validate
            - fileA.mmr
            - fileX.mmr
It may even not be a good idea to overwrite existing results without some kind of "force" setting anyway. Once this is addressed we can add the functionality quickly, let me know what you think, and thanks again. I've had 2 requests for this to be implemented already.

**Comment by mato7d5** [comment]
Hello Carl,
thank you for your time and code review. Absolutly, you are right. I did not consider the "-r" flag. Also I agree to create a mirror of source directory in directory with results to avoid for overwritting the reports.

I'll fix it to the end of this week if it's ok for you.

**Comment by carlwilson** [comment]
Perfect, I'll test and merge as soon as it's ready. Thanks muchly.

**Comment by mato7d5** [comment]
@carlwilson Hello Carl, 
I've pushed commit for following of input directory structure if recursive flag was defined on command line.

**Comment by carlwilson** [comment]
Hi Martin aka @mato7d5,
I've just tested this and I think there's an issue with the behaviour. The following is from the root of a fresh install with test corpus files. First up with relative paths:

    cfw@dm-wrkstn:~/verapdf/0.17$ ./verapdf -r --reportfolder ./results ./corpus/veraPDF-corpus-staging/PDF_A-1b/
    cfw@dm-wrkstn:~/verapdf/0.17$ ls -alh ./results/
    total 8.0K
    drwxrwxr-x  2 cfw cfw 4.0K Jun 22 15:12 .
    drwxrwxr-x 10 cfw cfw 4.0K Jun 22 15:12 ..
All of the output goes to `stdout` and there's nothing in the `results` folder, although it is created. Next up with absolute paths:

    cfw@dm-wrkstn:~/verapdf/0.17$ ./verapdf -r --reportfolder /home/cfw/verapdf/0.17/results /home/cfw/verapdf/0.17/corpus/veraPDF-corpus-staging/PDF_A-1b/
    cfw@dm-wrkstn:~/verapdf/0.17$ ls -alh ./results/
    total 16K
    drwxrwxr-x  4 cfw cfw 4.0K Jun 22 15:09 .
    drwxrwxr-x 10 cfw cfw 4.0K Jun 22 15:06 ..
    drwxrwxr-x  2 cfw cfw 4.0K Jun 22 15:09 6.4 Transparency
    drwxrwxr-x  2 cfw cfw 4.0K Jun 22 15:09 6.9 Interactive Forms
So two directories created, the rest to `stdout` again. Weird no? For reference the subdirs of the corpus directory are:

    cfw@dm-wrkstn:~/verapdf/0.17$ ls -al ./corpus/veraPDF-corpus-staging/PDF_A-1b/
    total 40
    drwxrwxr-x 10 cfw cfw 4096 Jun 22 14:55 .
    drwxrwxr-x  9 cfw cfw 4096 Jun 22 14:55 ..
    drwxrwxr-x 10 cfw cfw 4096 Jun 22 14:55 6.1 File structure
    drwxrwxr-x 11 cfw cfw 4096 Jun 22 14:55 6.2 Graphics
    drwxrwxr-x  5 cfw cfw 4096 Jun 22 14:55 6.3 Fonts
    drwxrwxr-x  2 cfw cfw 4096 Jun 22 14:55 6.4 Transparency
    drwxrwxr-x  3 cfw cfw 4096 Jun 22 14:55 6.5 Annotations
    drwxrwxr-x  4 cfw cfw 4096 Jun 22 14:55 6.6 Actions
    drwxrwxr-x  7 cfw cfw 4096 Jun 22 14:55 6.7 Metadata
    drwxrwxr-x  2 cfw cfw 4096 Jun 22 14:55 6.9 Interactive Forms
If you validate sub-directory by sub-directory and output to `results` then all is fine. I'm running a linux box:

    cfw@dm-wrkstn:~/git/veraPDF$ uname -a
    Linux dm-wrkstn 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    cfw@dm-wrkstn:~/git/veraPDF$ java -version
    openjdk version "1.8.0_91"
    OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
    OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by mato7d5** [comment]
Hello Carl,
yes, it's strange. I've tested it with my own directory structure and it worked fine. I'll take a look on it and use corpus too.

**Comment by mato7d5** [comment]
Hello Carl,
it's fixed. It was mistake. Used just mkdir() instead of mkdirs() what was the cause for problems with subdirs. It's strange, because previous solution worked for me. But it was my fault I used few files with 2 subdirs in main reportf folder (not subdir in subdir).

**Pull request merged**
