### PR TITLE
Use ~/.verapdf config directory on Linux.

### PR DESCRIPTION
**Pull request by marhop**
This may be a fix for the problem described in GitHub issue #113.

It sets the `app.home` property to `$HOME/.verapdf` in the shell scripts that start the application on Linux (Unix) systems. This essentially leads to creation of the directory `.verapdf/config/` in the user's home directory. Thus, no write permissions are needed anymore inside the program installation directory to run the application.

Cheers
Martin

### CODE REVIEW

**Comment by carlwilson** [comment]
Hi @marhop this does indeed look useful and fits in with our development plan. the truth be told, right now we're committed to making a release deadline and it's unlikely this will make it as we've had a lot of features to add ourselves. I'm keen not to repeat the work and would be happy to look at merging this next week when I can test it. Is there any chance you could update your branch on Monday (19/12), no worries if not as I'll pull in from the command line in that case. Thanks very much.

**Comment by marhop** [comment]
Hi Carl,

thanks for your reply! I can't make it on Monday, but probably on Tuesday or Wednesday, if this is sufficient.

Martin

**Comment by marhop** [comment]
Hi @carlwilson I just tried to update my branch but there are some merge conflicts with the integration branch which I don't quite understand. It seems to me as if my branch got mangled with pull request #109 somehow. Maybe it's easier if you indeed pull in from the command line?

Thanks!
Martin

**Comment by marhop** [comment]
Since this PR is close to four years old and I don't really remember its context anymore, I'll just close it due to housekeeping. ;-)

**Pull request closed without merging**
