### PR TITLE
FIX - STDIN warning:

### PR DESCRIPTION
**Pull request by carlwilson**
- output usage info when no parameter passed; and
- added instructions for terminal EOF to terminate STDIN processing.

### CODE REVIEW

**Comment by carlwilson** [comment]
This is an alternative solution to #52, as opposed to #54. This retains the STDIN processing but outputs help and instructions for gracefully terminating by issuing a terminal EOF. I'm open to arguments that @mato7d5 solution, i.e. #52, is more graceful, even I'm not sure I like mine best.

**Comment by mato7d5** [comment]
@carlwilson 
Your solution is better. Advanced users can still use pipes for processing PDF files from STDIN.
Please, reject my PR #54.

**Comment by carlwilson** [comment]
Hi @mato7d5 I was going to close this, we decided that advanced users could also supply a parameter and miss this warning. I'm going to leave as is for release 0.22 tomorrow but will leave this PR open and discuss with @beyo-ra and the veraPDF team. It's hard to know what to do for the best, I'm even considering the use of a special parameter to signal STDIN processing.

**Comment by mato7d5** [comment]
Hi @carlwilson 
Ok, thanks for info.

**Comment by carlwilson** [comment]
Hi @mato7d5 , and then we changed our mind again ;). All slightly comical.

**Pull request merged**
